### ISSUE TITLE
1.2.0 release note question

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-docker-extension#107]
>Prefer 'dockerd' in systemd unit files over 'docker daemon'. docker-engine has migrated to this. This is why we are releasing a minor version for the extension this time and not a hotfix so that existing VMs don’t automatically get this and old versions of docker will not work with dockerd.

Does that mean that users need to use a specific version of `azure-docker-extension` for certain images and a different version for other images? Or do all current images have a new enough version of `docker` and you're only worried about breaking people who haven't run package manager updates?

**Comment by ahmetalpbalkan** [comment]
> Does that mean that users need to use a specific version of azure-docker-extension for certain images and a different version for other images?

Not really. If a new VM that does not have a docker-engine NOT installed:

- 1.1 will work for all images except centos (as get.docker.com script broke downstream)
- 1.2 will work for all images including centos

We install docker-engine via get.docker.com script so it has nothing to do with distros' package manager updates and such.

If this release was a hotfix release and got picked up by VMs that have older versions of Docker installed (which is most of them), extension would think the systemd unit file is not in its goal state (since we changed `docker daemon` to `dockerd` now in this last version) and it'd just update it and thus break the existing setup.

By making a minor release we make sure _mostly_ the new VMs get it. That said, if you have older versions of docker installed (those who don't have dockerd binary) and docker extension NEVER installed, then you'll run into issues, saying _dockerd not found_.

Does this help?

**Comment by colemickens** [comment]
Yes, thank you.
