### ISSUE TITLE
Provide newest version of docker-compose

### ISSUE THREAD

**Issue by mrmunch** [Azure/azure-docker-extension#113]
I just installed DockerExtension on a new VM.
I can see, there is the latest version of docker - but a very old version of docker-compose.
Please also provide the latest version of docker-compose when installing this extension!

**Comment by boumenot** [comment]
Thanks for opening an issue!  
> (future-self) The extension installs 1.6.2, and the latest release is 1.9.0.  

I do not know why @ahmetalpbalkan did not update to a later version of docker-compose because this version is about a year old.  There are several breaking changes between 1.6.2 and 1.9.0.  Is there specific functionality you need or bug fixes that require 1.9.0, or is this a general request.

**Comment by mrmunch** [comment]
When I created this request it was general. 
But now I'd like to get compose@v1.10.0 with this Extension because I want to use compose with docker@v1.13.0 for Docker Swarm scenarios.

**Comment by boumenot** [comment]
@colemickens provided an update regarding Docker Swarm in #115.  Docker Swarm is outside the scope of this extension, but I think Cole provided an good alternative.

**Comment by fcatae** [comment]
+1. 
I have problems with a deployment using version 2.1. I am using a user defined network to provide static IP address.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
