### ISSUE TITLE
Docker Extension with 'login' setting always failed with ''docker login' failed' on docker 17.06.0-ce 

### ISSUE THREAD

**Issue by hebinhuang** [Azure/azure-docker-extension#131]
It looks the failure caused by --email parameter. It does not support --email parameter.

matrixadmin@StateManagerDev01:~$ docker login --email
unknown flag: --email
See 'docker login --help'.

matrixadmin@StateManagerDev01:~$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
- /var/log/azure-docker-extension-enable.log
[azure-docker-extension-enable.log.txt](https://github.com/Azure/azure-docker-extension/files/1119256/azure-docker-extension-enable.log.txt)

- /var/log/waagent.log
[waagent.log.txt](https://github.com/Azure/azure-docker-extension/files/1119262/waagent.log.txt)

**Comment by schlaup** [comment]
It has been a month and it is still broken.

Did you find a workaround?

Thanks!

**Comment by schlaup** [comment]
The current version of Docker Extension is not compatible with the current version of Docker.

The bug has been reported two month ago and there is a PR to fix it that has not been accepted yet. This project seems to be dead.

Since the extension is published but not maintained by Microsoft there is nothing that the community can do about.

My workaround was to get rid of the Docker Extension in my project and replace it with CoreOS and cloud-init to install and setup docker. (With the additional advantage that you can then easily move it to other cloud providers like Google cloud.)

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
