### ISSUE TITLE
Docker container state under Azure Docker Extensions

### ISSUE THREAD

**Issue by mpilant** [Azure/azure-docker-extension#46]
I was under the impression Docker containers were stateless.  In other words, exiting a running container and starting it would cause a "fresh" instance to start up, nothing from the previous run would be "remembered".  Am I correct in believing containers should be stateless?
I am asking because I am seeing cases (not all the time) where the state from a running container persists across a container exit.
I'm trying to understand whether I'm seeing a bug or If this in the intended behavior.

**Comment by ahmetalpbalkan** [comment]
@mpilant sorry I couldn't understand the question or the problem here. Can you please explain what are you doing with examples along with what is happening vs what is the behavior you expect?

**Comment by mpilant** [comment]
@ahmetalpbalkan No problem. :-)  I have an app running in a container, and the web interface allows various characteristics to be changed.  For example, switch from one database to another.  Worth noting is there isn't a default, so if one or the other is not chosen, operations (via the web interface) which require a DB will fail (as expected / by design).
What I have seen is in most cases, after the container exits and it is started, if the DB is not chosen the subsequent operations will fail (as expected).  However, on a couple of occasions, I have seen situations where the operation will succeed using the DB chosen before the container exited.
The DB choice is an example of the "state" to which I'm referring.
Stateless, I would expect the container start to require the DB choice every time.  Statelful I would expect the previous choice to be "remembered".
Does this help?

**Comment by ahmetalpbalkan** [comment]
@mpilant I think your question is about Docker itself, please refer to their user guide and try to use it by installing it youself without using this extension. 

This extension helps you do the following:
- install Docker engine on your VMs
- create an initial set of containers (if specified). 

Please refer to this repository's home and check out the User Guide for more info about what this extension is doing. 

From what I understood your question is about the nature of Docker containers and their runtime, so closing this issue. Feel free to comment if otherwise, I can reopen.
