### ISSUE TITLE
Docker version as configuration

### ISSUE THREAD

**Issue by lalyos** [Azure/azure-docker-extension#74]
It would be usefull to be able to fix down the docker version you want to use.
Right now the drivers are implementing the installation as `curl -sSL https://get.docker.com/ | sh` 
which always gets the latest version.

A workaround could be to let `https://get.docker.com/` install the latest, and if the `docker_version` is specified, we add an extra `yum install docker-engine-${DOCKER_VERSION}` or `apt-get wahtever`

Does it makes sense?

**Comment by ahmetalpbalkan** [comment]
@lalyos eventually we'd love to provide this feature. Currently are installing the latest version (mostly because get.docker.com script does not take a version number). However we are eventually hoping to get rid of get.docker.com script as docker tends to break every now and then. See: #62.

Also, we probably need to evaluate how this applies to CoreOS etc as you can’t really install docker there. It comes readonly with the OS image.

I agree that this is a valid ask.

**Comment by jjjordanmsft** [comment]
+1.  We've been having some serious issues with 1.12 that didn't show up in 1.10 or 1.11 and would prefer to not install it on newer machines.

**Comment by ahmetalpbalkan** [comment]
@jjjordanmsft I strongly suggest not using docker extension for that purpose for now. You can find installation instructions to install a specific version at https://docs.docker.com.

**Comment by marty2bell** [comment]
Guys

After tearing my hair out trying to get a docker install just the way I would like it, this template came the closest albeit I would have liked to have docker-compose 1.8 installed rather than 1.6.  

Appreciate everyone has different needs, but if we could specify the version we need in the extension json that would provide the flexibility for different needs without locking anyone into an opinionated view of what version of docker is the right one......

**Comment by ahmetalpbalkan** [comment]
@marty2bell unfortunately, that is currently sort of a ton of work to make it work on many different distros we support today. The `get.docker.com` script does not provide a way to specify the docker-engine version unfortunately.

Every time we bump version of docker-compose or something, we end up breaking some distro/version combo we are supporting in this extension (such as older versions of CoreOS) because many docker components are not always backwards compatible (or docker-compose specifically raises errors like "docker version of client is newer than the server").

We end up in this situation where we need to support a lot of distros and many versions of them with many versions of docker-engine and docker-compose. It's a quite sad place to be at nowadays and not really sustainable in the long term.



What I can suggest is, try using cloud-init (the customData field of the VMs) to install docker-engine using the instructions at https://docs.docker.com/ and docker-compose as you like. It is easier than you would think and works nicely as well.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
