### ISSUE TITLE
Compose error details are not propagated to Ibiza or CLI

### ISSUE THREAD

**Issue by alinamstanciu** [Azure/azure-docker-extension#86]
If docker-compose throws an error, the error details are not propagated to either Ibiza or the CLI.

**Comment by ahmetalpbalkan** [comment]
@alinamstanciu this is mostly because we directly invoke `docker-compose` binary, which prints arbitrary output instead of a structured one. I believe we should not rely on their output format and try to parse out something meaningful.

Here is a failure:

```
Pulling sleep (busyboxs:latest)...
Error: image library/busyboxs not found
```

Here is another:

```
Validation failed in file '/etc/docker/compose/docker-compose.yml', reason(s):
Unsupported config option for 'sleep' service: 'commands'
```

As you see, totally unstructured.

Would a better error message such as `docker-compose failed with exit code 1, check out /var/log/.../docker-extension.log` be more helpful to you?

**Comment by vishwam** [comment]
Would it be possible to just pass-through the stderr contents when the exit code is not 0? Otherwise, the error message you suggested is good as well.
(Also, since docker-compose can be flakey at times, could you add some logic to retry docker-compose a second time in case of failure?)

**Comment by ahmetalpbalkan** [comment]
@vishwam For now I just added the path of the log file that contains the docker-compose error to the error message that goes to the portal. This is effective in v1.1.1606092330

I have some concerns about adding retries as re-running `docker-compose up` has certain semantics about already running containers. Feel free to open another issue if not having retries really impacts you.
